### ISSUE TITLE
[FEATURE REQUEST] Implement a description for git jargon embedded in the description of the command and flags

### ISSUE THREAD

**Issue by nezia1** [Nezia1/what-the-git#10]
**Is your feature request related to a problem? Please describe.**
I was thinking about this as the next big step towards an actually useful app even for seasoned developers. The idea behind this is that it should highlight words such as "staging area" in the description.

**Describe the solution you'd like**
I would like it to be embedded in the description of the command, and when you hover it it shows a small description of what that specific term means, and it also can contain a link towards a full article. I was thinking about having a separate folder, and having articles written in markdown that we could parse using a third-party library. 

**Describe alternatives you've considered**
The only alternative I can see is only having a hyperlink to the article, but I figured that would be bad for user experience. In an ideal scenario, it would also show a short description when hovering over the link.

**Additional context**
Pardon my poor paint skills, but I think this shows pretty well what I want to achieve:
https://imgur.com/TNRcOtn

**Comment by ReedyBear** [comment]
That image looks really nice & I think that's a great idea, as long as you're interested in writing those articles or seeking out contributors for them.

**Comment by nezia1** [comment]
> That image looks really nice & I think that's a great idea, as long as you're interested in writing those articles or seeking out contributors for them.

I was thinking about it! For now I'm just gonna implement the definitions but later on I'm going to tackle the markdown articles system. I would really like it if someone could design some graphs as well to explain how the staging area works for example, so it still has the feel of the app. I could find some online too, but ideally we want to have a consistent theme.

**Comment by nezia1** [comment]
Merged manually due to merge conflicts.
