### ISSUE TITLE
[FEATURE REQUEST] Improve documentation

### ISSUE THREAD

**Issue by nezia1** [Nezia1/what-the-git#11]
**Is your feature request related to a problem? Please describe.**
I would really like if the documentation could be improved, I feel like it's not good enough so far and it could use a bit of refactoring.

**Describe the solution you'd like**
I was thinking about adding some screenshots? Some nice looking screenshots would be really welcome as an introduction to the app. It would make the front page a bit more welcoming.

**Comment by lghiggino** [comment]
Hey Nezia1, I'd like to contribute on this issue. This will be my first documentation improvement on GH. Could you be more specific on how you would want it to be? Maybe, could you refer me to a couple examples that you consider to be well done?

**Comment by nezia1** [comment]
I found this list of good looking README files if that can help: https://github.com/matiassingers/awesome-readme
I looked at them a bit and consider them to be good example of what we should be aiming for.

**Comment by lghiggino** [comment]
ok. Working on it based on the list
